### PR TITLE
Update environment.yaml

### PR DESCRIPTION
**Pull request by fnattino**
Added required packages for the Dask/STAC intro

### CODE REVIEW

**Comment by fnattino** [comment]
Could you also update the environment in the shared Software folder @cpranav93 ?

**Comment by cpranav93** [comment]
Will do it this weekend.

**Comment by fnattino** [comment]
I have realised the env file matching the environment on Spider was not this one, but the one in the [JupyterDaskOnSLURM (workshops branch)](https://github.com/RS-DAT/JupyterDaskOnSLURM/tree/workshops). For now, I have updated the two of them to have them matching (with this PR and [this one](https://github.com/RS-DAT/JupyterDaskOnSLURM/pull/35)), to avoid possible confusion. After the workshops, we should probably clean up the JupyterDaskOnSLURM repo to leave it workshop agnostic.

**Review by cpranav93 — APPROVED** [review]
All good, merging it.

**Pull request merged**
