### PR TITLE
Created notebooks for code-along

### PR DESCRIPTION
**Pull request by cpranav93**
I have created a draft template for the code-along where complicated functions have been left in the notebook. I have a couple of discussion points:
1) Should we keep the functions for calculations within the notebook or take it out to another file?
2) How much description should we leave in the notebook?

### CODE REVIEW

**Comment by fnattino** [comment]
Hi @cpranav93, thanks again for starting this! I have created a simplified notebook for the data-retrieval part. As I have mentioned today I am a bit afraid that working with the real notebook from the phenology use case might be overwhelming for participants. I am thus thinking about doing something along the line of what shown in [this notebook](notebooks/01-download-Daymet4_simplified.ipynb): 

* start off by showing around a STAC catalog saved on disk, maybe just consisting of a dozen satellite scenes, so that people get an idea of how catalogs look in practice (=a bunch of directories and JSON files)
* show how to construct a MINIMAL catalog for Daymet linking to the remote NetCDF files (see notebook linked above). Save the catalog on the Spider filesystem
* show how data files can be downloaded using the STAC2dCache utility function
* show how we can open the REAL Daymet catalog from dCache

Thinking more to this I am convinced that we should avoid having participants writing to dCache (reading is fine). They would be writing to the same project space, potentially overwriting each other's work and/or important stuff (I am thinking we should share a read-only token with them). Would you agree? Also pinging @meiertgrootes

**Comment by meiertgrootes** [comment]
I tend to agree on the read-only access to dCache @fnattino @cpranav93 . Maybe add the code for a save to dCache as "further info" in the notebook after the example where the catalog is saved to the spider nfs. That way they could use it for future reference, as well as see how the operation is completely analougous beween nfs and dCache when using STAC2dCache

**Comment by cpranav93** [comment]
@fnattino, is the code-along for reading the stac catalog ready? If so, we can merge this branch.

**Comment by fnattino** [comment]
I will probably update details of it, but we can merge it

**Comment by cpranav93** [comment]
I see now that there is the filled in version. Do you want to have an empty one with only the first few cells filled up?

**Comment by fnattino** [comment]
Added the filled and the empty ones!

**Pull request merged**
